### ISSUE TITLE
[Question] failed to create host: Image windows-default is not supported

### ISSUE THREAD

**Issue by itscaro** [CircleCI-Public/windows-preview-docs#16]
I ran into this error:

```
failed to create host: Image windows-default is not supported
```
Pipeline: https://circleci.com/gh/roboll/helmfile/8981

I configure the yaml file as:

```
  test_windows:
    machine:
      image: windows-default
    working_directory: C:\workspace\helmfile
```

Cf https://github.com/roboll/helmfile/pull/1754

Could you tell me what do I do wrong here please?
